name: tutorials-indexer

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 6"

jobs:
  youtube-playlists-indexer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Run Butter youtube playlist indexer
      uses: bennymeg/youtube-playlists-action@v1
      with:
        channel-id: UC3RGu86BjqnUToMvttPmhJA
        api-key: ${{ secrets.YOUTUBE_API_TOKEN }}
        output-directory: docs/butter
        
    - name: Run Blender youtube playlist indexer
      uses: bennymeg/youtube-playlists-action@v1
      with:
        channel-id: UCSMOQeBJ2RAnuFungnQOxLg
        api-key: ${{ secrets.YOUTUBE_API_TOKEN }}
        output-directory: docs/blender
        max-results: 50
        
    - name: Commit playlists data
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated tutorials index
        commit_user_name: Butter Bot
        commit_user_email: butter.robotics@gmail.com
        commit_author: bennymeg <bennymegk@gmail.com>
        
    - name: Assert workflow active
      uses: gautamkrishnar/keepalive-workflow@v1
      with:
        committer_username: Benny Bot
        committer_email: butter.robotics@gmail.com
