name: toturials-indexer

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  youtube-playlists-indexer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Run youtube playlist indexer
      uses: bennymeg/youtube-playlists-action@v1
      with:
        channel-id: UCBadW1_E7CPAt9pxFWVnqkQ # UC3RGu86BjqnUToMvttPmhJA
        token: ${{ secrets.YOUTUBE_API_TOKEN }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated toturials index
        commit_user_name: Butter Bot
        commit_user_email: butter.robotics@gmail.com
        commit_author: bennymeg <bennymegk@gmail.com>
